### ISSUE TITLE
Can this be achieved with save_model.py using file formats other than .weights files

### ISSUE THREAD

**Issue by Meliordass** [hasantha-nirmal/speed_violation_detection_yolo#3]
Hello, I encountered a problem when training the .weights file, so I would like to ask if it is possible to use other types of files such as .pth or .h5, etc., and convert them to pb files through save_model.py. I will be very happy if you can reply, best wishes.

**Comment by hasantha-nirmal** [comment]
Hi. theoretically yes. You can train the models with different format. Depends on how accurately you can do the conversion. Might need to go with the trial and error. I would suggest to use ChatGPT to recommend a proper way of the conversion.

Regards

**Comment by hasantha-nirmal** [comment]
Since no feedback, I'm closing the case.
